[ISSUE-297] Fix imbue after skill level up
SDClowen/RSBot pull request #298
Opened 2022-06-10 10:30 UTC by ngoedde

!closes #297

2022-06-11 17:04 UTC, SDClowen requested changes

2022-06-11 17:04 UTC, myildirimofficial commented on Plugins/RSBot.Skills/Views/Main.cs
> +                    var refSkill = Game.ReferenceManager.GetRefSkill(resurrectionSkillId);
The result can be null. Can you add null check?

2022-06-11 17:04 UTC, myildirimofficial commented on Plugins/RSBot.Skills/Views/Main.cs
> +                    var refSkill = Game.ReferenceManager.GetRefSkill(selectedImbue);
The result can be null. Can you add null check?

2022-06-12 06:27 UTC, ngoedde commented on Plugins/RSBot.Skills/Views/Main.cs
> +                    var refSkill = Game.ReferenceManager.GetRefSkill(selectedImbue);
Done

2022-06-12 06:27 UTC, ngoedde commented on Plugins/RSBot.Skills/Views/Main.cs
> +                    var refSkill = Game.ReferenceManager.GetRefSkill(resurrectionSkillId);
Done

2022-06-12 13:47 UTC, merged